
service: sls-visits-count


custom:
  GREETER_DYNAMODB_TABLE: sls-unit-test-names-table
  VISITS_COUNT_DYNAMODB_TABLE: sls-visits-count-table

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
      Resource: 
        Fn::GetAtt:
          - GreeterTable
          - Arn
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
      Resource: 
        Fn::GetAtt:
          - VisitsTable
          - Arn
        

functions:
  hello:
    handler: handler.hello
    description: "Just hello world"
    events: 
    - http:
        path: hello
        method: get
        cors: true
  moi:
    handler: handler.moi
    description: "save the name to a database and says hi"
    events:
      - http:
          path: moi
          method: get
          cors: true
  wasGreeted:
    handler: handler.wasGreeted
    description: "return 200 if the name was created, 404 if not"
    events:
    - http:
        path: greet
        method: get
        cors: true
  newVisit:
    handler: handler.newVisit
    description: "Add visit count"
    events: 
    - http:
        path: newVisit
        method: get
        cors: true 

resources:
  Resources:
    GreeterTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.GREETER_DYNAMODB_TABLE}
    VisitsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "visits"
          AttributeType: "N"
        KeySchema:
        - AttributeName: "visits"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.VISITS_COUNT_DYNAMODB_TABLE}
    