
service: sls-visits-count

custom: 
  GREETER_DYNAMODB_TABLE: sls-visits-count-node

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
      Resource: 
        Fn::GetAtt:
          - GreeterTable
          - Arn
        

functions:
  hello:
    handler: handler.hello
    description: "Just hello world"
    events: 
    - http:
        path: hello
        method: get
        cors: true
        private: true
  moi:
    handler: handler.moi
    description: "save the name to a database and says hi"
    events:
      - http:
          path: moi
          method: get
          cors: true
          private: true
  wasGreeted:
    handler: handler.wasGreeted
    description: "return 200 if the name was created, 404 if not"
    events:
    - http:
        path: greet
        method: get
        cors: true
        private: true
    

resources: # CloudFormation template syntax from here on.
  Resources:
    GreeterTable:
      Type: AWS::DynamoDB::Table
      BillingMode: PAY_PER_REQUEST
      Properties:
        TableName: ${self:custom.GREETER_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1