
service: sls-visits-count
provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    handler: handler.hello
    description: "Just hello world"
    events: 
    - http:
        path: hello
        method: get
        cors: true
        private: true
    
